version : 2
updates : 
  - package-ecosystem : "npm"
    directory : "/back"
    schedule : 
      interval : "daily"
    labels:
      - 'ðŸ¤–Â° dependabot'
    commit-message:
      prefix: '[BACK DEPS]'
  - package-ecosystem : "npm"
    directory : "/client"
    schedule :
      interval : "daily"
    labels:
      - 'ðŸ¤–Â° dependabot'
    commit-message:
      prefix: '[FRONT DEPS]'